#Exercício Python 9: Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
numero = int(input('Digite um número inteiro:'))
print ('A tabuada do número {} é:'.format(numero))
print ('{} * 1 = {}'.format(numero,numero * 1))
print ('{} * 2 = {}'.format(numero,numero * 2))
print ('{} * 3 = {}'.format(numero,numero * 3))
print ('{} * 4 = {}'.format(numero,numero * 4))
print ('{} * 5 = {}'.format(numero,numero * 5))
print ('{} * 6 = {}'.format(numero,numero * 6))
print ('{} * 7 = {}'.format(numero,numero * 7))
print ('{} * 8 = {}'.format(numero,numero * 8))
print ('{} * 9 = {}'.format(numero,numero * 9))
print ('{} * 10 = {}'.format(numero,numero * 10))